// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycswtygwjoswcpmjeueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljc3d0eWd3am9zd2NwbWpldWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTAzMjAsImV4cCI6MjA2OTc2NjMyMH0.3dOTfBpJdHcXBXx6FWBpq8KSZI459c1Ck1dX8yy5YnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});